language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: MReyRdOo+FZwQzAilZ5U1G2KsTTau8JJJcqjwmE3pF42k8/a/g7bpnNyoBYfdhEl7nQ6k7RjprhjN0fGYwDK9vkZcf/TB/zX0T95On9ewuXuwVTBh00PZY1aFkMawRtQESIN9JfPbdrpwUanZD+J1nEQ5DbKQKlB5yxNk0WzHuwR0rEEs7nOFkMpsx+cpDidNLnd+/6IgDQ4Hq5lrkOYU7byWfLsC8Hna3wt3ESgdU5qtG2YUZ6QCBNKDA/dDNvvQ6enMqVk0f5Qb49PPt2obcxZxYGDzEQtCBaa95frV2XoSVPJvsTQY5zJRbjHPosxElrCQKJIZZneonfXRuZ9Fd5bUhglIM3TVLPrD5s3D1Q3ggZvG3na8fAKLV5FdX5R8/QpqdTywlEyEcaCRfL0SfmIqxGDogMyMhE7fcEhO3gjJ+AuKJK57uwyMuhx7Y8VAvSdU+M+lApvIeB5O4G1RhkIdEzat27kRbZ2sczyF/62h+0tuECbc6K9V6hL845hFCOa3syVvv00xVsg1vcp4SDfffZR4taU5d7rX0n/fzl5bi5DO7wDRxU7s7VKwj/HxrGrO4k7Dto5iNd1/NXF1PB2WW5rWUVejd3Uof4Kgrp7TxhBbbw17hKwfUCTquRSdF/jOGGFEqEXERYQdq/mbYbSq3xgRlhGH8EfhLaQsf4=
  app: bgh-server
  on: master
